### PR TITLE
Bug states

### PR DESCRIPTION
**Pull request by mythmon**
Add bug state (Not Ready, Ready, Started, In Review, Merged, Done). This takes the form of a new store, and is also shown in the UI (though it is really ugly right now).

r?

### CODE REVIEW

**Comment by mythmon** [comment]
Also, I realized that this doesn't account for blocking bugs when determining state.

**Comment by willkg** [comment]
This looks good as far as I can tell. You wrote up an issue for the blocking stuff, so I think I'd just toss a comment in the code and push that off until later.

**Comment by mythmon** [comment]
With all the styling, it looks like this, if you're curious (I think Heroku is going to have some deploy problems, sadly)

screenshot

**Comment by willkg** [comment]
Wow! Nice! Why didn't we ditch ernest ages ago?

**Pull request merged**
