### PR TITLE
Update most imports to pull from index.js modules.

### PR DESCRIPTION
**Pull request by mythmon**
A few didn't work with the new patter. Added comments to these. Maybe problems with circular imports or import order?

@willkg if you have any insights about the few that can't use this pattern, I'm really puzzled.

NB: Circular imports can work fine in ES6, with some caveats. In this way it is different from Python.

### CODE REVIEW

**Comment by willkg** [comment]
Is it correct to say that importing BaseStore with the new pattern never works?

**Comment by mythmon** [comment]
I'd be comfortable saying that. I have never seen it work. Though I don't know why.

**Comment by mythmon** [comment]
@willkg Any thing you'd like to see different about this PR? Otherwise I think we should merge it.

**Comment by willkg** [comment]
I haven't had time to really read about how imports and ES6 work and all that and I'm not sure I'm going to have time tomorrow. I don't think this should block on me.

Possibilities: Ask someone else who would know more? pomax? jlongster? r1cky? someone else with react/flux/ES6 knowledge?

**Pull request merged**
