### PR TITLE
Fix title to be context-sensitive

### LINKED ISSUE #51: title should be "edwin - <product>"
If you've got multiple edwin tabs open, then it's impossible to distinguish between them because the title in both cases is "Edwin".

I think we should change it to "Edwin - {product}".

Are there other options?

### PR DESCRIPTION
**Pull request by willkg**
Fixes #51 

This is kind of goofy, but I didn't see a better way to do it since the title is outside the react universe.

r?

### CODE REVIEW

**Comment by willkg** [comment]
Also, this creates a "Edwin - <THING>" kind of thing. In issue #51, you mentioned doing it in reverse. Do you want to switch to "<THING> - Edwin"?

**Comment by mythmon** [comment]
That is supremely goofy, but it seems like it would work.

In this state, I don't think I'll benefit from this. My tabs are rarely wide enough to see past "Edwin -". But then, I'm weird. I think "Edwin -" makes more sense more of the time, even if I can't see it.

**Comment by willkg** [comment]
I'll switch it around, then.

**Comment by willkg** [comment]
^^^ That reverses the title.

**Pull request merged**
