### PR TITLE
Re-organize imports, add import linter, and make things prettier.

### PR DESCRIPTION
**Pull request by mythmon**
The major changes here:
1. Add import/export linting
2. Add `index.js` files to re-export everything in a folder in one place.
3. Rewrite most import stanzas to take advantage of 2, saving lots of space.

@willkg thoughts?

### CODE REVIEW

**Comment by mythmon** [comment]
The reorganization generally reduced (or kept the same) the number of lines for imports in each file, and reduced the amount of times that you have to type the same thing twice on an import line (like `import foo from '../bar/foo.js'` becomes `import foo from '../bar/`).

**Comment by willkg** [comment]
There's a failing test.

It looks good to me. Definitely easier to write than before. Plus I like the rearrangement of constants.

**Comment by mythmon** [comment]
Turns out that something is wrong. Either Babel actually doesn't support this import pattern, or something else is wrong. The web page doesn't even load right now due to really early errors. I suspect the test is a symptom of that.

**Comment by mythmon** [comment]
I can't figure out what went wrong here. I split out the first half of this into #70, and I'll work on the second half with a bit more diligence next.

**Pull request closed without merging**
